In [1]:
#import numpy package 
import numpy as np


In [2]:
#creat empty array
arr=np.array([])
print(arr)
print(type(arr))

[]
<class 'numpy.ndarray'>


In [3]:
#creat numpy to store value such as 2,3,4,5,6,7
arr1=np.array([2,3,4,5,6,7])
print(arr1)
print(type(arr1))

[2 3 4 5 6 7]
<class 'numpy.ndarray'>


In [5]:
#creat numpy array to store values such blue,green,yellow,white,black,orange
colours=np.array(("blue","green","yellow","white","black","orange"))
print(colours)
print(type(colours))


['blue' 'green' 'yellow' 'white' 'black' 'orange']
<class 'numpy.ndarray'>


In [7]:
#how to create an array using list 
List=[12,13,14,23,44,23]
arr=np.array(List)
print(arr)
print(type(arr))

[12 13 14 23 44 23]
<class 'numpy.ndarray'>


In [9]:
#how to create an array using tuple 
Tuple=(12,43,45,56,12,34)
arr2=np.array(Tuple)
print(arr2)
print(type(arr2))

[12 43 45 56 12 34]
<class 'numpy.ndarray'>


## 1 -D Array


In [2]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr)
print("Dimension of array is",arr.ndim)
print("Number of elements is",arr.size)
print("Data type of an array elements",arr.dtype)

[1 2 3 4 5 6]
Dimension of array is 1
Number of elements is 6
Data type of an array elements int64


## 2-D Array ---- matrices

In [14]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
arr_2d=np.array([[4,5,6,7],[8,9,1,2],[3,2,4,3],[9,2,1,4]])
print(arr_2d)
print(type(arr_2d))
print("Dimension of aarray is",arr_2d.ndim)
print("Number of elements is ",arr_2d.size) 
print("Order if matrix is",arr_2d.shape)

[[4 5 6 7]
 [8 9 1 2]
 [3 2 4 3]
 [9 2 1 4]]
<class 'numpy.ndarray'>
Dimension of aarray is 2
Number of elements is  16
Order if matrix is (4, 4)


## 3-D Array____

In [21]:
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr)
print("Dimension of aarray is",arr.ndim)
print("Number of elements is ",arr.size) 
print("Order if matrix is",arr.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
Dimension of aarray is 3
Number of elements is  9
Order if matrix is (1, 3, 3)


## Built in function to generate numpy array

In [ ]:
#arange: It is used to generate evenly spaced values within a given interval
note: end valus is not included 

In [22]:
#generate the values from 0 to 14
np.arange(15) #end valus is not included 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
#generate the valus from 0 t0 30 
np.arange(31)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [24]:
#generate valus from 100 to 150
#arange (start,end)
np.arange(100,151)

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [25]:
#generate valus from 400 to 480
np.arange(400,481)

array([400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412,
       413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425,
       426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438,
       439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451,
       452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464,
       465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477,
       478, 479, 480])

In [29]:
#generate first 10 even number 
#arange (start,end,step)
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [30]:
#generate an array which is includes 10 multiples of 5
np.arange(5,51,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [31]:
#generate an array which is include 10 multipe of 8
np.arange(8,81,8)

array([ 8, 16, 24, 32, 40, 48, 56, 64, 72, 80])

## Ones

In [32]:
# ones : returns an array with all one 
#return 1-D array with 3 elements as 1
np.ones(3)

array([1., 1., 1.])

In [33]:
#return 1-D array 10 elemnts as 1
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## 2-D Array

In [35]:
#create matrix of order (2,2)
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [36]:
#create unit matrix of order (3,5)
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [37]:
#create unit matrix of order (5,3)
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Zeros

In [38]:
#return 1-D array 10 elemnts as 0
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [39]:
#create matrix of order (2,2)
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [40]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## eye--identity

In [41]:
#create (2,2) identity matrix
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [42]:
#create (3,3) identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
#create (4,3) identity matrix
np.eye(4,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

## Full--It is used to generate array with same ekements 

In [3]:
#create (2,2) all elements as 10
np.full((2,2),10)

array([[10, 10],
       [10, 10]])

In [4]:
#create (4,3) all elements as 20
np.full((4,3),20)

array([[20, 20, 20],
       [20, 20, 20],
       [20, 20, 20],
       [20, 20, 20]])

## Linspace--It is used to generate linearly spaced values  

In [48]:
#generate linearly spaced values of 1 to 5
np.linspace(1,5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [49]:
#generate 10 equaly linearly spaced values 1 to 100
np.linspace(1,100,num=10,retstep=True)

(array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.]),
 np.float64(11.0))

In [51]:
#generate 10 equaly linearly spaced values 1 to 1000
np.linspace(1,1000,num=10,retstep=True)

(array([   1.,  112.,  223.,  334.,  445.,  556.,  667.,  778.,  889.,
        1000.]),
 np.float64(111.0))

In [53]:
np.linspace(1,100,num=10,retstep=False)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])